### ISSUE TITLE
A space is missing before Outshine word in the mode line

### ISSUE THREAD

**Issue by Mat-R** [alphapapa/outshine#71]
In the mode line where I can see every modes used in the current buffer, there is a space before each mode name (except Emacs-Lisp; maybe because it is the first one) but not for Outshine. As a consequence, the mode written just before Outshine will not be separated to Outshine.

![Screenshot from 2019-06-16 00-49-30](https://user-images.githubusercontent.com/36885389/59557084-b5f1c100-8fd0-11e9-8f26-eb0c1eef2647.png)

**Comment by Mat-R** [comment]
In the mode line where I can see every modes used in the current buffer, there is a space before each mode name but not for Outshine. As a consequence, the mode written just before Outshine will not be separated to Outshine.

![Screenshot from 2019-06-16 00-49-30](https://user-images.githubusercontent.com/36885389/59557084-b5f1c100-8fd0-11e9-8f26-eb0c1eef2647.png)

**Comment by thblt** [comment]
Hello,

The space in a minor mode lighter (that's what it's called) goes *after* the name. Outshine has it:

https://github.com/alphapapa/outshine/blob/master/outshine.el#L737

My guess is that the issue is with the mode with the "hs" lighter. Can you try deactivating it to confirm?

**Comment by thblt** [comment]
Sorry, I wrote too fast. There's no issue with hs, you should probably update Outshine, this was fixed long ago: see #39.

**Comment by Mat-R** [comment]
Hello,

Thank you for your comment. I installed Outshine yesterday  but it was through MELPA stable so I think it is not fixed there. I confirm it is fixed using MELPA.

Thank you.
